[package]
name = "botgame"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
aery = "0.5.2"
bevy = "0.12"
bevy_mod_index = "0.3.0"
extension-trait = "1.0.2"
wasm-bindgen = "0.2.89"
